/** Static demo ledger: Lagos, Abuja, Kano and key routes — no DB */
export const DEMO_SHIPMENTS = [
  { id: "demo-1", trackingId: "DMX-1001", customerName: "Mubarak Ventures", receiverName: "Abuja Depot", destination: "Abuja", receiverPhone: "+234 801 234 5678", serviceOption: "Express", status: "In-Transit", packageWeight: 4.2, cost: 4500, paymentStatus: "Paid", createdAt: "12 Feb 2026" },
  { id: "demo-2", trackingId: "DMX-1002", customerName: "GreenLife Pharma", receiverName: "Kano North", destination: "Kano", receiverPhone: "+234 802 345 6789", serviceOption: "Economy", status: "Delivered", packageWeight: 6, cost: 8200, paymentStatus: "Paid", createdAt: "14 Feb 2026" },
  { id: "demo-3", trackingId: "DMX-1003", customerName: "Lagos Boutique", receiverName: "Lekki Store", destination: "Lagos", receiverPhone: "+234 803 456 7890", serviceOption: "Express", status: "Pending", packageWeight: 5, cost: 6000, paymentStatus: "Pending", createdAt: "15 Feb 2026" },
  { id: "demo-4", trackingId: "DMX-1004", customerName: "Abuja Essentials", receiverName: "VI Office", destination: "Lagos", receiverPhone: "+234 804 567 8901", serviceOption: "Economy", status: "Delivered", packageWeight: 2, cost: 2500, paymentStatus: "Paid", createdAt: "15 Feb 2026" },
  { id: "demo-5", trackingId: "DMX-1005", customerName: "Port Harcourt Goods", receiverName: "Wuse 2 Desk", destination: "Abuja", receiverPhone: "+234 805 678 9012", serviceOption: "Express", status: "Delivered", packageWeight: 3.5, cost: 5200, paymentStatus: "Paid", createdAt: "14 Feb 2026" },
  { id: "demo-6", trackingId: "DMX-1006", customerName: "Ibadan Market Co.", receiverName: "Kano Central", destination: "Kano", receiverPhone: "+234 806 789 0123", serviceOption: "Economy", status: "In-Transit", packageWeight: 7, cost: 7100, paymentStatus: "Paid", createdAt: "13 Feb 2026" },
  { id: "demo-7", trackingId: "DMX-1007", customerName: "The Lagos Paparazzi", receiverName: "Ikeja Hub", destination: "Lagos", receiverPhone: "+234 807 890 1234", serviceOption: "Express", status: "Pending", packageWeight: 2.5, cost: 3800, paymentStatus: "Unpaid", createdAt: "15 Feb 2026" },
  { id: "demo-8", trackingId: "DMX-1008", customerName: "Mubarak Ventures", receiverName: "Gwagwalada", destination: "Abuja", receiverPhone: "+234 808 901 2345", serviceOption: "Express", status: "Delivered", packageWeight: 9, cost: 9000, paymentStatus: "Paid", createdAt: "12 Feb 2026" },
];
